spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bus_reserve?useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&createDatabaseIfNotExist=true
    username: postgres
    password: admin08
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  security:
    user:
      name: admin
      password: 123456
      roles: ADMIN

server:
  port: 8080
  error:
    include-message: always
main:
  allow-bean-definition-overriding: true
  lazy-initialization: true

app:
  jwt-secret: 2e58d90f853e8552168c378d4c7edb9e466c514da9798d1a90235d8e52fe470b
  jwt.expiration-milliseconds: 72000000